apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  template:
    spec:
      containers:
        - name: auth
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"