apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restauranty-staging

resources:
- ../../base
- namespace.yaml
- auth-hpa.yaml
- discounts-hpa.yaml
- items-hpa.yaml
- client-hpa.yaml

images:
- name: fatemehparmoo/restauranty-auth
  newName: fatemehparmoo/restauranty-auth
  newTag: ea64dde
- name: fatemehparmoo/restauranty-client
  newName: fatemehparmoo/restauranty-client
  newTag: staging-ea64dde
- name: fatemehparmoo/restauranty-discounts
  newName: fatemehparmoo/restauranty-discounts
  newTag: ea64dde
- name: fatemehparmoo/restauranty-items
  newName: fatemehparmoo/restauranty-items
  newTag: ea64dde
    
patches:
- path: patches/auth-deployment.yaml
- path: patches/discounts-deployment.yaml
- path: patches/items-deployment.yaml
- path: patches/client-deployment.yaml
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: restauranty-ingress
